export const AUTO_CONDITION_SKILL = "AUTO_CONDITION_SKILL";
export type AUTO_CONDITION_SKILL = typeof AUTO_CONDITION_SKILL;

export const AUTO_CONDITION_ARCHETYPE = "AUTO_CONDITION_ARCHETYPE";
export type AUTO_CONDITION_ARCHETYPE = typeof AUTO_CONDITION_ARCHETYPE;
