export const DISCOUNT_CHI = "DISCOUNT_CHI";
export type DISCOUNT_CHI = typeof DISCOUNT_CHI;

export const DISCOUNT_SKILL = "DISCOUNT_SKILL";
export type DISCOUNT_SKILL = typeof DISCOUNT_SKILL;

export const DISCOUNT_LORESHEET = "DISCOUNT_LORESHEET";
export type DISCOUNT_LORESHEET = typeof DISCOUNT_LORESHEET;

export const DISCOUNT_LORESHEET_OPTION = "DISCOUNT_LORESHEET_OPTION";
export type DISCOUNT_LORESHEET_OPTION = typeof DISCOUNT_LORESHEET_OPTION;

export const DISCOUNT_KUNGFU_STYLE = "DISCOUNT_KUNGFU_STYLE";
export type DISCOUNT_KUNGFU_STYLE = typeof DISCOUNT_KUNGFU_STYLE;

export const DISCOUNT_KUNGFU_TECHNIQUE = "DISCOUNT_KUNGFU_TECHNIQUE";
export type DISCOUNT_KUNGFU_TECHNIQUE = typeof DISCOUNT_KUNGFU_TECHNIQUE;

export const DISCOUNT_VIRTUE = "DISCOUNT_VIRTUE";
export type DISCOUNT_VIRTUE = typeof DISCOUNT_VIRTUE;
