export const EFFECT_COMBAT_STATISTIC = "EFFECT_COMBAT_STATISTIC";
export type EFFECT_COMBAT_STATISTIC = typeof EFFECT_COMBAT_STATISTIC;

export const EFFECT_CONDITIONAL_TEXT = "EFFECT_CONDITIONAL_TEXT";
export type EFFECT_CONDITIONAL_TEXT = typeof EFFECT_CONDITIONAL_TEXT;

export const EFFECT_CHI_THRESHOLD_INCREASE_BASE_CHI =
  "EFFECT_CHI_THRESHOLD_INCREASE_BASE_CHI";
export type EFFECT_CHI_THRESHOLD_INCREASE_BASE_CHI = typeof EFFECT_CHI_THRESHOLD_INCREASE_BASE_CHI;
