version: 2
jobs:
  build:
    working_directory: ~/gentilboulet/LotWCS
    parallelism: 1
    docker: # run the steps with Docker       
    - image: circleci/node:10.7.0
    steps: # a collection of executable commands
    - checkout # special step to check out source code to working directory     
    - run: 
        name: update-npm
        command: 'sudo npm install -g npm@latest' 
    - restore_cache: # special step to restore the dependency cache      
        key: dependency-cache-{{ checksum "package.json" }} 
    - run:
        name: install-npm-wee 
        command: npm install   
    - save_cache: # special step to save the dependency cache    
        key: dependency-cache-{{ checksum "package.json" }}        
        paths:        
          - ./node_modules     
    - run: # linter
        name: tslint
        command: ./node_modules/tslint/bin/tslint --project .
    - run: # run tests       
        name: test      
        command: npm test    
    - run: # run coverage report          
        name: code-coverage 
        command: 'npm run coverage-test'
    - run: # send to coveralls
        name: coveralls
        command: 'npm run coveralls'
    - store_artifacts: # special step to save test results as as artifact    
        path: test-results.xml     
        prefix: tests   
    - store_artifacts:   
        path: coverage          
        prefix: coverage      
    - store_test_results: # special step to upload test results for display in Test Summary          
        path: test-results.xml
