export const BONUS_REDUCTION = 'BONUS_REDUCTION';
export type BONUS_REDUCTION = typeof BONUS_REDUCTION;

export const BONUS_DESTINY = 'BONUS_DESTINY';
export type BONUS_DESTINY = typeof BONUS_DESTINY;

export const BONUS_ENTANGLEMENT = 'BONUS_ENTANGLEMENT';
export type BONUS_ENTANGLEMENT = typeof BONUS_ENTANGLEMENT;

export const BONUS_STARTING_CHI = 'BONUS_STARTING_CHI';
export type BONUS_STARTING_CHI = typeof BONUS_STARTING_CHI;
