export const LORESHEET_OPEN = 'LORESHEET_OPEN';
export type LORESHEET_OPEN = typeof LORESHEET_OPEN;

export const LORESHEET_BUY_BONUS = 'LORESHEET_BUY_BONUS';
export type LORESHEET_BUY_BONUS = typeof LORESHEET_BUY_BONUS;
