export const REDUCTION_SKILL = 'REDUCTION_SKILL';
export type REDUCTION_SKILL = typeof REDUCTION_SKILL;

export const REDUCTION_LORESHEET = 'REDUCTION_LORESHEET';
export type REDUCTION_LORESHEET = typeof REDUCTION_LORESHEET;

export const REDUCTION_LORESHEET_OPTION = 'REDUCTION_LORESHEET_OPTION';
export type REDUCTION_LORESHEET_OPTION = typeof REDUCTION_LORESHEET_OPTION;
