export const HEADER_SET_NAME = 'HEADER_SET_NAME';
export type HEADER_SET_NAME = typeof HEADER_SET_NAME;

export const HEADER_SET_CONCEPT = 'HEADER_SET_CONCEPT';
export type HEADER_SET_CONCEPT = typeof HEADER_SET_CONCEPT;

export const HEADER_SET_ARCHETYPE = 'HEADER_SET_ARCHETYPE';
export type HEADER_SET_ARCHETYPE = typeof HEADER_SET_ARCHETYPE;

export const HEADER_SET_RANK = 'HEADER_SET_RANK';
export type HEADER_SET_RANK = typeof HEADER_SET_RANK;
