export const KUNGFU_OPEN_STYLE = 'KUNGFU_OPEN_STYLE';
export type KUNGFU_OPEN_STYLE = typeof KUNGFU_OPEN_STYLE;

export const KUNGFU_CUSTOM_NAME_FOR_STYLE = 'KUNGFU_CUSTOM_NAME_FOR_STYLE';
export type KUNGFU_CUSTOM_NAME_FOR_STYLE = typeof KUNGFU_CUSTOM_NAME_FOR_STYLE;

export const KUNGFU_CUSTOM_NAME_FOR_TECHNIQUE = 'KUNGFU_CUSTOM_NAME_FOR_TECHNIQUE';
export type KUNGFU_CUSTOM_NAME_FOR_TECHNIQUE = typeof KUNGFU_CUSTOM_NAME_FOR_TECHNIQUE;

export const KUNGFU_BUY_TECHNIQUE = 'KUNGFU_BUY_TECHNIQUE';
export type KUNGFU_BUY_TECHNIQUE = typeof KUNGFU_BUY_TECHNIQUE;
