export const LORESHEET_OPEN = 'LORESHEET_OPEN';
export type LORESHEET_OPEN = typeof LORESHEET_OPEN;

export const LORESHEET_BUY_OPTION = 'LORESHEET_BUY_OPTION';
export type LORESHEET_BUY_OPTION = typeof LORESHEET_BUY_OPTION;
