export const BONUS_DISCOUNT = 'BONUS_DISCOUNT';
export type BONUS_DISCOUNT = typeof BONUS_DISCOUNT;

export const BONUS_DESTINY = 'BONUS_DESTINY';
export type BONUS_DESTINY = typeof BONUS_DESTINY;

export const BONUS_ENTANGLEMENT = 'BONUS_ENTANGLEMENT';
export type BONUS_ENTANGLEMENT = typeof BONUS_ENTANGLEMENT;

export const BONUS_CHI = 'BONUS_CHI';
export type BONUS_CHI = typeof BONUS_CHI;

export const BONUS_CULTIVATION = 'BONUS_CULTIVATION';
export type BONUS_CULTIVATION = typeof BONUS_CULTIVATION;

export const BONUS_ONE_AMONG_N = 'BONUS_ONE_AMONG_N';
export type BONUS_ONE_AMONG_N = typeof BONUS_ONE_AMONG_N;

export const BONUS_SKILL_RANK = 'BONUS_SKILL_RANK';
export type BONUS_SKILL_RANK = typeof BONUS_SKILL_RANK;

export const BONUS_SPECIALITY = 'BONUS_SPECIALITY';
export type BONUS_SPECIALITY = typeof BONUS_SPECIALITY;
